# SoundHash Frontend Service
# Add this to the root docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000/api/v1}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-ws://localhost:8000/ws}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-SoundHash}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - app  # Backend service
    networks:
      - soundhash-network
    restart: unless-stopped

networks:
  soundhash-network:
    driver: bridge
