"""Unit tests for authentication utilities (password and API key hashing/verification)."""

import pytest

from src.api.auth import (
    get_password_hash,
    hash_api_key,
    verify_api_key,
    verify_password,
)


class TestPasswordHashing:
    """Tests for password hashing and verification."""

    def test_password_hash_and_verify(self):
        """Test that a password can be hashed and verified."""
        password = "SecurePassword123!"
        hashed = get_password_hash(password)

        # Hash should use bcrypt format
        assert hashed.startswith("$2b$"), "Hash should use bcrypt format"

        # Correct password should verify
        assert verify_password(password, hashed), "Should verify correct password"

    def test_password_verify_incorrect(self):
        """Test that incorrect password fails verification."""
        password = "SecurePassword123!"
        hashed = get_password_hash(password)

        # Wrong password should not verify
        assert not verify_password("WrongPassword", hashed), "Should not verify wrong password"

    def test_password_salt_randomness(self):
        """Test that the same password produces different hashes due to salt."""
        password = "SamePassword123!"

        hash1 = get_password_hash(password)
        hash2 = get_password_hash(password)

        # Same password should produce different hashes
        assert hash1 != hash2, "Same password should produce different hashes due to salt"

        # Both should verify correctly
        assert verify_password(password, hash1), "Should verify against first hash"
        assert verify_password(password, hash2), "Should verify against second hash"

    def test_password_backward_compatibility_with_passlib(self):
        """Test that we can verify passlib-generated bcrypt hashes."""
        # This is a real bcrypt hash generated by passlib for "test_password"
        passlib_hash = "$2b$12$Qix8AmYhaSW10/Z9VQiv8uUNlx03Qy2i1xD.Mb0YYZsrmXnFVGWNy"

        # Should verify correct password
        assert verify_password("test_password", passlib_hash), "Should verify passlib hash"

        # Should not verify wrong password
        assert not verify_password(
            "wrong_password", passlib_hash
        ), "Should not verify wrong password"

    def test_password_verify_malformed_hash(self):
        """Test that malformed hash returns False instead of raising exception."""
        password = "TestPassword123!"

        # Various malformed hashes should return False, not raise
        assert not verify_password(password, ""), "Empty hash should return False"
        assert not verify_password(password, "invalid_hash"), "Invalid hash should return False"
        assert not verify_password(
            password, "$2b$12$invalid"
        ), "Incomplete bcrypt hash should return False"
        assert not verify_password(
            password, "not_a_bcrypt_hash"
        ), "Non-bcrypt hash should return False"

    def test_password_verify_wrong_hash_type(self):
        """Test that wrong type for hash returns False instead of raising exception."""
        password = "TestPassword123!"

        # None should be handled gracefully
        assert not verify_password(password, None), "None hash should return False"


class TestAPIKeyHashing:
    """Tests for API key hashing and verification."""

    def test_api_key_hash_and_verify(self):
        """Test that an API key can be hashed and verified."""
        api_key = "sk_test_key_12345678901234567890"
        hashed = hash_api_key(api_key)

        # Hash should use bcrypt format
        assert hashed.startswith("$2b$"), "Hash should use bcrypt format"

        # Correct key should verify
        assert verify_api_key(api_key, hashed), "Should verify correct API key"

    def test_api_key_verify_incorrect(self):
        """Test that incorrect API key fails verification."""
        api_key = "sk_test_key_12345678901234567890"
        hashed = hash_api_key(api_key)

        # Wrong key should not verify
        assert not verify_api_key(
            "sk_wrong_key_12345678901234567890", hashed
        ), "Should not verify wrong key"

    def test_api_key_salt_randomness(self):
        """Test that the same API key produces different hashes due to salt."""
        api_key = "sk_same_key_12345678901234567890"

        hash1 = hash_api_key(api_key)
        hash2 = hash_api_key(api_key)

        # Same key should produce different hashes
        assert hash1 != hash2, "Same API key should produce different hashes due to salt"

        # Both should verify correctly
        assert verify_api_key(api_key, hash1), "Should verify against first hash"
        assert verify_api_key(api_key, hash2), "Should verify against second hash"

    def test_api_key_verify_malformed_hash(self):
        """Test that malformed hash returns False instead of raising exception."""
        api_key = "sk_test_key_12345678901234567890"

        # Various malformed hashes should return False, not raise
        assert not verify_api_key(api_key, ""), "Empty hash should return False"
        assert not verify_api_key(api_key, "invalid_hash"), "Invalid hash should return False"
        assert not verify_api_key(
            api_key, "$2b$12$invalid"
        ), "Incomplete bcrypt hash should return False"
        assert not verify_api_key(
            api_key, "not_a_bcrypt_hash"
        ), "Non-bcrypt hash should return False"

    def test_api_key_verify_wrong_hash_type(self):
        """Test that wrong type for hash returns False instead of raising exception."""
        api_key = "sk_test_key_12345678901234567890"

        # None should be handled gracefully
        assert not verify_api_key(api_key, None), "None hash should return False"


class TestCrossCompatibility:
    """Tests for cross-compatibility between password and API key functions."""

    def test_different_passwords_different_hashes(self):
        """Test that different passwords produce different hashes."""
        password1 = "Password1"
        password2 = "Password2"

        hash1 = get_password_hash(password1)
        hash2 = get_password_hash(password2)

        # Different passwords should produce different hashes
        assert hash1 != hash2, "Different passwords should produce different hashes"

        # Each should only verify against its own
        assert verify_password(password1, hash1), "Password1 should verify against hash1"
        assert verify_password(password2, hash2), "Password2 should verify against hash2"
        assert not verify_password(password1, hash2), "Password1 should not verify against hash2"
        assert not verify_password(password2, hash1), "Password2 should not verify against hash1"

    def test_different_api_keys_different_hashes(self):
        """Test that different API keys produce different hashes."""
        key1 = "sk_key1_12345678901234567890123"
        key2 = "sk_key2_12345678901234567890123"

        hash1 = hash_api_key(key1)
        hash2 = hash_api_key(key2)

        # Different keys should produce different hashes
        assert hash1 != hash2, "Different API keys should produce different hashes"

        # Each should only verify against its own
        assert verify_api_key(key1, hash1), "Key1 should verify against hash1"
        assert verify_api_key(key2, hash2), "Key2 should verify against hash2"
        assert not verify_api_key(key1, hash2), "Key1 should not verify against hash2"
        assert not verify_api_key(key2, hash1), "Key2 should not verify against hash1"
