"""Webhook models for event notifications."""

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from .auth import User
    from .tenant import Tenant


class Webhook(Base):  # type: ignore[misc,valid-type]
    """Webhook endpoint configuration for event notifications."""

    __tablename__ = "webhooks"

    id: Mapped[int] = mapped_column(primary_key=True)
    tenant_id: Mapped[int | None] = mapped_column(ForeignKey("tenants.id"))
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))

    # Webhook configuration
    url: Mapped[str] = mapped_column(String(2048))
    description: Mapped[str | None] = mapped_column(String(500))
    secret: Mapped[str] = mapped_column(String(255))  # HMAC secret for signature verification

    # Event subscriptions (array of event types)
    events: Mapped[dict] = mapped_column(JSON)  # e.g., ["match.found", "video.processed"]

    # Status and rate limiting
    is_active: Mapped[bool] = mapped_column(default=True)
    rate_limit_per_minute: Mapped[int | None] = mapped_column(default=60)

    # Custom headers (JSON object)
    custom_headers: Mapped[dict | None] = mapped_column(JSON)

    # Statistics
    total_deliveries: Mapped[int | None] = mapped_column(default=0)
    successful_deliveries: Mapped[int | None] = mapped_column(default=0)
    failed_deliveries: Mapped[int | None] = mapped_column(default=0)
    last_delivery_at: Mapped[datetime | None] = mapped_column()
    last_success_at: Mapped[datetime | None] = mapped_column()
    last_failure_at: Mapped[datetime | None] = mapped_column()

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    user: Mapped["User"] = relationship("User")  # type: ignore[assignment]
    deliveries: Mapped[list["WebhookDelivery"]] = relationship("WebhookDelivery", back_populates="webhook", cascade="all, delete-orphan")  # type: ignore[assignment]


class WebhookEvent(Base):  # type: ignore[misc,valid-type]
    """Log of webhook events generated by the system."""

    __tablename__ = "webhook_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    tenant_id: Mapped[int | None] = mapped_column(ForeignKey("tenants.id"))

    # Event information
    event_type: Mapped[str] = mapped_column(String(100))  # e.g., "match.found"
    event_data: Mapped[dict] = mapped_column(JSON)  # Full event payload
    resource_id: Mapped[str | None] = mapped_column(String(255))  # ID of the resource (e.g.)
    resource_type: Mapped[str | None] = mapped_column(String(100))  # Type of resource (e.g.)

    # Processing status
    processed: Mapped[bool] = mapped_column(default=False)
    processed_at: Mapped[datetime | None] = mapped_column()

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))

    # Relationships
    deliveries: Mapped[list["WebhookDelivery"]] = relationship("WebhookDelivery", back_populates="event", cascade="all, delete-orphan")  # type: ignore[assignment]


class WebhookDelivery(Base):  # type: ignore[misc,valid-type]
    """Track webhook delivery attempts and results."""

    __tablename__ = "webhook_deliveries"

    id: Mapped[int] = mapped_column(primary_key=True)
    webhook_id: Mapped[int] = mapped_column(ForeignKey("webhooks.id", ondelete="CASCADE"))
    event_id: Mapped[int] = mapped_column(ForeignKey("webhook_events.id", ondelete="CASCADE"))

    # Delivery details
    attempt_number: Mapped[int] = mapped_column(default=1)
    status: Mapped[str] = mapped_column(String(50))  # "pending", "success", "failed", "retrying"
    
    # Request/Response
    request_headers: Mapped[dict | None] = mapped_column(JSON)
    request_body: Mapped[str | None] = mapped_column(Text)
    response_status_code: Mapped[int | None] = mapped_column()
    response_headers: Mapped[dict | None] = mapped_column(JSON)
    response_body: Mapped[str | None] = mapped_column(Text)
    error_message: Mapped[str | None] = mapped_column(Text)

    # Timing
    duration_ms: Mapped[int | None] = mapped_column()  # Response time in milliseconds
    next_retry_at: Mapped[datetime | None] = mapped_column()  # For failed deliveries with retry

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    delivered_at: Mapped[datetime | None] = mapped_column()
    updated_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    webhook: Mapped["Webhook"] = relationship("Webhook", back_populates="deliveries")  # type: ignore[assignment]
    event: Mapped["WebhookEvent"] = relationship("WebhookEvent", back_populates="deliveries")  # type: ignore[assignment]
