apiVersion: v1
kind: ConfigMap
metadata:
  name: soundhash-config
  namespace: soundhash-production
data:
  # Database configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "soundhash"
  DATABASE_POOL_SIZE: "10"
  DATABASE_MAX_OVERFLOW: "20"
  DATABASE_POOL_TIMEOUT: "30"
  DATABASE_POOL_RECYCLE: "3600"
  DATABASE_STATEMENT_TIMEOUT: "30000"
  
  # Redis configuration
  REDIS_ENABLED: "true"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  CACHE_TTL_SECONDS: "300"
  
  # API configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_TITLE: "SoundHash API"
  API_VERSION: "1.0.0"
  API_DESCRIPTION: "Audio fingerprinting and matching API"
  API_ALGORITHM: "HS256"
  API_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  API_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  API_RATE_LIMIT_PER_MINUTE: "60"
  API_CORS_ORIGINS: "https://soundhash.io,https://api.soundhash.io,https://www.soundhash.io"
  
  # Multi-tenant
  BASE_DOMAIN: "soundhash.io"
  
  # Processing configuration
  TEMP_DIR: "/app/temp"
  MAX_CONCURRENT_DOWNLOADS: "3"
  MAX_CONCURRENT_CHANNELS: "2"
  SEGMENT_LENGTH_SECONDS: "90"
  FINGERPRINT_SAMPLE_RATE: "22050"
  
  # Caching
  YT_DLP_CACHE_DIR: "/app/cache/yt-dlp"
  ENABLE_YT_DLP_CACHE: "true"
  
  # Similarity thresholds
  SIMILARITY_CORRELATION_THRESHOLD: "0.70"
  SIMILARITY_L2_THRESHOLD: "0.70"
  SIMILARITY_MIN_SCORE: "0.70"
  SIMILARITY_CORRELATION_WEIGHT: "0.5"
  SIMILARITY_L2_WEIGHT: "0.5"
  
  # Logging
  LOG_LEVEL: "INFO"
  
  # Environment
  ENVIRONMENT: "production"
