apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: soundhash-api-hpa
  namespace: soundhash-production
  labels:
    app: soundhash
    component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soundhash-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU utilization target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    # Scale down behavior
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down by max 50% of current pods
        periodSeconds: 60
      - type: Pods
        value: 2  # Or scale down by max 2 pods
        periodSeconds: 60
      selectPolicy: Min  # Use the policy that results in fewer pods removed
    # Scale up behavior
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
      - type: Percent
        value: 100  # Scale up by max 100% of current pods
        periodSeconds: 30
      - type: Pods
        value: 4  # Or scale up by max 4 pods
        periodSeconds: 30
      selectPolicy: Max  # Use the policy that results in more pods added
