apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: soundhash-production
data:
  pgbouncer.ini: |
    [databases]
    # NOTE: Update host to your actual database endpoint (RDS or in-cluster service)
    soundhash = host=RDS-ENDPOINT-OR-SERVICE-NAME port=5432 dbname=soundhash
    
    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    
    # Pool configuration
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 25
    reserve_pool_size = 5
    reserve_pool_timeout = 3
    
    # Connection lifetime
    server_lifetime = 3600
    server_idle_timeout = 600
    server_connect_timeout = 15
    
    # Logging
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    
    # Performance tuning
    query_timeout = 30
    query_wait_timeout = 120
    client_idle_timeout = 0
    idle_transaction_timeout = 0
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: soundhash-production
  labels:
    app: pgbouncer
    component: database-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
        component: database-proxy
    spec:
      initContainers:
      - name: init-userlist
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "\"$DB_USER\" \"$DB_PASSWORD\"" > /etc/pgbouncer/userlist.txt
          chmod 600 /etc/pgbouncer/userlist.txt
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: soundhash-secrets
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: soundhash-secrets
              key: database-password
        volumeMounts:
        - name: userlist
          mountPath: /etc/pgbouncer
      
      containers:
      - name: pgbouncer
        image: pgbouncer/pgbouncer:1.21.0
        ports:
        - containerPort: 6432
          name: pgbouncer
          protocol: TCP
        
        # Environment variables for configuration
        # NOTE: These are for reference; actual connection is configured via pgbouncer.ini
        env:
        - name: POSTGRESQL_HOST
          value: "RDS-ENDPOINT-OR-SERVICE-NAME"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: soundhash-secrets
              key: database-name
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: soundhash-secrets
              key: database-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: soundhash-secrets
              key: database-password
        
        volumeMounts:
        - name: config
          mountPath: /etc/pgbouncer/pgbouncer.ini
          subPath: pgbouncer.ini
          readOnly: true
        - name: userlist
          mountPath: /etc/pgbouncer/userlist.txt
          subPath: userlist.txt
          readOnly: true
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
        livenessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 15
          periodSeconds: 20
        
        readinessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 5
          periodSeconds: 10
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: config
        configMap:
          name: pgbouncer-config
      - name: userlist
        emptyDir:
          medium: Memory
      
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: soundhash-production
  labels:
    app: pgbouncer
    component: database-proxy
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
  - name: pgbouncer
    port: 6432
    targetPort: 6432
    protocol: TCP
  sessionAffinity: None
